# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='ex.protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nbase.proto\x12\tex.protos\"\x15\n\x04\x42\x61se\x12\r\n\x05\x66ield\x18\x01 \x01(\x08\x62\x06proto3'
)




_BASE = _descriptor.Descriptor(
  name='Base',
  full_name='ex.protos.Base',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='ex.protos.Base.field', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=46,
)

DESCRIPTOR.message_types_by_name['Base'] = _BASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Base = _reflection.GeneratedProtocolMessageType('Base', (_message.Message,), {
  'DESCRIPTOR' : _BASE,
  '__module__' : 'base_pb2'
  # @@protoc_insertion_point(class_scope:ex.protos.Base)
  })
_sym_db.RegisterMessage(Base)


# @@protoc_insertion_point(module_scope)
