# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ext.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import base_pb2 as base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ext.proto',
  package='ex.protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\text.proto\x12\tex.protos\x1a\nbase.proto\"$\n\x03\x45xt\x12\x1d\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x0f.ex.protos.Baseb\x06proto3'
  ,
  dependencies=[base__pb2.DESCRIPTOR,])




_EXT = _descriptor.Descriptor(
  name='Ext',
  full_name='ex.protos.Ext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='ex.protos.Ext.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=72,
)

_EXT.fields_by_name['base'].message_type = base__pb2._BASE
DESCRIPTOR.message_types_by_name['Ext'] = _EXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ext = _reflection.GeneratedProtocolMessageType('Ext', (_message.Message,), {
  'DESCRIPTOR' : _EXT,
  '__module__' : 'ext_pb2'
  # @@protoc_insertion_point(class_scope:ex.protos.Ext)
  })
_sym_db.RegisterMessage(Ext)


# @@protoc_insertion_point(module_scope)
